[book]
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
multilingual = false
src = "src"
title = "The Tock Book"

[output.html]
additional-css = ["theme/pagetoc.css", "theme/pagetoc-tock.css", "theme/tabs.css"]
additional-js  = ["theme/pagetoc.js", "theme/tabs.js"]

[preprocessor.pagetoc]

[preprocessor.chapter-list]

[output.linkcheck]
optional = true
exclude = [ '.*trd.*', 'TockBinaryFormat', '.*spdx.*', '.*CommandZeroSemantics.*' ]

[preprocessor.webinclude]

[preprocessor.tabs]
